name: roboventure
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  android_icon_name: "ic_launcher_roboventure"

  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true